### PR TITLE
Styled the landing page and fixed the background image for login page…

### PR DESCRIPTION
**Pull request by Timwestberg**
…, Im prett sure i fixed issue with travis as well hoping we will stop receiving errors from the prettier package

### CODE REVIEW

**Review by jelmished — COMMENTED** [review]
Code looks good. Maybe down the road we'll change "content" class to something more explicit. E.g. "background_img".

**Review by narasimhan-ramesh5 — APPROVED** [review]

**Comment by narasimhan-ramesh5** [comment]
Approving changes

**Comment by narasimhan-ramesh5** [comment]
Approving changes

**Review by erikcedillo — APPROVED** [review]
Approved

**Pull request merged**
